name: Test Action
run-name: "Pipeline Github Action"
env:
  ENV_WORKFLOW: "This value was set in workflow file"
on:    
  push:
    branches:
      - main
      - feature/*

jobs:
  say_hello:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Print current working directory
      run: pwd

    - name: Execute bash file
      run: sh say_hello.sh
    
    - name: Expressions
      run: |
        echo ${{ 1 }}
        echo ${{ 'Strign expression' }}
        echo ${{ 2 > 3  }}
    
    - name: Print github action context object
      run: |
        echo '${{ toJson(github) }}'
        echo '${{ toJson(job) }}'
        echo '${{ toJson(secrets) }}'
        echo '${{ toJson(steps) }}'
        echo '${{ toJson(runner) }}'

    - name: Print Environment Variables
      run: |
        echo $ENV_WORKFLOW
        echo '${{ vars.ENV_MESSAGE }}'

  run_feature_branch :
    runs-on: ubuntu-latest
    if: startsWith(github.ref , 'refs/heads/feature/')
    steps:
    - uses: actions/checkout@v3
    
    - name: Print current working directory
      run: pwd

    - name: Execute bash file
      run: sh say_hello.sh
    
    - name: Expressions
      run: |
        echo ${{ 1 }}
        echo ${{ 'Strign expression' }}
        echo ${{ 2 > 3  }}
    
    - name: Print github action context object
      run: |
        echo '${{ toJson(github) }}'
        echo '${{ toJson(job) }}'
        echo '${{ toJson(secrets) }}'
        echo '${{ toJson(steps) }}'
        echo '${{ toJson(runner) }}'
  